apiVersion: batch/v1
kind: Job
metadata:
  name: "install-local-path"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: default
      restartPolicy: OnFailure
      containers:
        - name: install-local-path
          image: bitnami/kubectl:1.33-debian-12
          imagePullPolicy: IfNotPresent
          command: [ "sh", "-c" ]
          args:
            - |
              set -e
              # install local-path provisioner manifest (Rancher official manifest)
              curl -fsSL https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml \
                | kubectl apply -f -
              # ensure storageclass exists and mark it default (idempotent)
              if kubectl get storageclass local-path >/dev/null 2>&1; then
                kubectl patch storageclass local-path -p '{"metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}' || true
              fi