apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  hostPath:
    path: /mnt/data
  persistentVolumeReclaimPolicy: Retain