apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm
spec:
  project: default
  source:
    helm:
      valueFiles:
        - values.lgtm.yaml
        - values.alloy.yaml
        - values.beyla.yaml
      # values: |
        
    repoURL: https://github.com/aidenharwood/portfolio-helm-lgtm
    targetRevision: HEAD
    path: .
  destination:
    name: in-cluster
    namespace: lgtm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true