apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm
spec:
  project: default
  source:
    helm:
      values: |

    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.1.0
    chart: lgtm-distributed
  destination:
    name: in-cluster
    namespace: lgtm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true