apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website
spec:
  project: default
  source:
    helm:
    repoURL: https://github.com/aidenharwood/portfolio-helm-website
    targetRevision: HEAD
    path: .
  destination:
    name: in-cluster
    namespace: website
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true