apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- target:
  group: apps
  version: v1
  kind: Deployment
  name: coredns
  namespace: kube-system
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: coredns
      namespace: kube-system
    spec:
      replicas: 2